### ISSUE TITLE
Bunnyland: Puff Trees

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#100]
The drops

1x carrot 35%
2x nuts 90%
1x wood 100%
1x bunny puff  80%

**Comment by Snook-8** [comment]
Also IF possible have them entirely replace the birchnut trees, in ALL biomes

**Comment by Snook-8** [comment]
Also IF possible have them replace Evergreen trees, if any of them is left in Bunnyland.

**Comment by jchmb** [comment]
Done. I did change the drops a bit to integrate them better.
