### ISSUE TITLE
Bunnyland: Bunnymen with beehat have wrong animations and textures

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#111]
thats pretty unsettling and major, they are clunky and are using parts of the WEREPIGS animations and also a weird mixture of the BEARDLORDS textures and drops! I think it needs an imidiate fix. 

![bug1](https://user-images.githubusercontent.com/20684392/43361427-02b8d1f6-92d7-11e8-8fd3-90bdfafbbfb8.png)

**Comment by jchmb** [comment]
This is more likely a DST bug.

**Comment by YiinHikari** [comment]
Well bunnyman in DST work fine, with that hat, walking and attacking, works normal. I just tested. It is more worrying for me right now that the files of that bunnymen are not found in the entire mod. I made and issue of that

**Comment by YiinHikari** [comment]
It works fine with the live version of the mod, walking, attacking, the rabbit behaves normal, so I will close the issue:
![20190501213236_1](https://user-images.githubusercontent.com/25496851/57051671-eff14880-6c58-11e9-80c6-3cf0bcbd9d9e.jpg)
![20190501213220_1](https://user-images.githubusercontent.com/25496851/57051675-f5e72980-6c58-11e9-82eb-951d23ccdc49.jpg)
