### ISSUE TITLE
Tab Icons missing?

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#114]
as quoted from Yin "Oh btw I noticed the first day i step into the server that some things don't have a proper icon in the crafting tab. You just tell me whenever i can be helpful with something :)"

expecting more clarification for the momen.

**Comment by YiinHikari** [comment]
I can confirm that the "altar" icon is the same as the "salt rack" on the crafting tab (both are a "salt rack" icon). Will see for the others.
