### ISSUE TITLE
Snowland: Snow Bunnymen UPDATE

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#123]
I made a new texture for the Snow Bunnymen.  The .png file is uploaded to the WIP folder as "Bunnymen_snow"
You guys rename it for however it fits for the coding. It must be a relatively _simple_ replacement of the current files that Snowland's bunnymen use which I think they are named like Bunnymen_blue? or something like that

Also do **remove** the badly recolored winter hat like this 
![20180630230526_1](https://user-images.githubusercontent.com/20684392/44945792-7c144d00-adf8-11e8-8992-157e57561e64.jpg)

and just let them wear the vanilla one 
http://dontstarve.wikia.com/wiki/Winter_Hat

Thanks

**Comment by Snook-8** [comment]
Health 220
Damage 25
Attack Period 2 
Attack Range 2
Walking Speed 2.5
Running speed 4
Chill Aura (Like the Chillpigs)
Special Ability: Whenever is fed with carrot it poops ice
Sanity Aura +25/min (when allied)

Drop Loot:
 x1 carrot 100% 
x1 ice  90%
x1 Bunny Puff 30%
x1 Blueprint for their hut 25%

**Comment by Snook-8** [comment]
![bunnyman_snow](https://user-images.githubusercontent.com/20684392/44962238-f1317080-af25-11e8-81a5-f3f4b9f3ead4.png)

Im testing if texture files can be successfully shared here.

**Comment by Snook-8** [comment]
Oh that seems effecient (I think)

**Comment by YiinHikari** [comment]
yes they definitely can. Good idea n_n

**Comment by jchmb** [comment]
Resolved. :)
