### ISSUE TITLE
Crates: invisible or visible

### ISSUE THREAD

**Issue by YiinHikari** [jchmb/dst-multiverse#126]
I am so confused. I see the crates are invisible in the server, but, with the same files and code (directly from the workshop) they are visible on my game when i start a new word. Not only in multiland but also in Volcanoland alone. I don't understand why in the multiverse server they are invisible but they works perfectly fine in a -hosted- new generated word... 

UPDATE: 

Well since the server had a recent restart i am pretty sure now: In the public server, the crates are definitely invisible in the world, while beeing visible in the map. I don't know how, but the code that you get from the workshop when you suscribe to the mod in working okay, the crates are not invisible. So i guess we have to fix the server, not the mod, since it works fine at it is.

**Comment by jchmb** [comment]
Should be fixed now. This issue occurs when The Gorge Port is enabled, since it has a name with the same prefab. I assume this changes the way the assets are loaded, which may have caused the bug.
