### ISSUE TITLE
Roboland: Robopigs houses: Balance change

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#127]
![20180907021709_1](https://user-images.githubusercontent.com/20684392/45190015-577b0380-b244-11e8-969d-6ac22a2b954e.jpg)
![20180907021714_1](https://user-images.githubusercontent.com/20684392/45190016-577b0380-b244-11e8-8691-2eb838146ea9.jpg)

Either I'm drunk or the houses are drunk.

Can we spread them a bit? And lessen them? They are kind of gamebreaking like this, making it too difficult to farm them not to mention the danger they produce for WX-78 players. Also the way they are sto stuck on the road makes it look like a bug?

**Comment by jchmb** [comment]
Fixed.
