### ISSUE TITLE
Rename/Fix the bugged prefabs for mod compatibility

### ISSUE THREAD

**Issue by Saiph300** [jchmb/dst-multiverse#53]
The following files cause a crash with Shipwrecked-related mods:

https://imgur.com/a/hqDMTa1

This is because if you define prefabs that other mods use (ex: dragoon) they will be loaded even if you don't use them. The loading order is the reverse of priority (The Volcanic biome is priority 0, so your dragoon is loaded instead of their)

To allow users to play with both mods it would be great if you could remove/rename the above list of files as well as comment the following in Prefabfiles:

"dragoon",
"dragoonden",
"dragoonheart",
"dragoonspit",
"dragoonfire",

**Comment by jchmb** [comment]
I'll just fix them, since we're going in that direction anyway.

**Comment by jchmb** [comment]
Fixed. Working versions have now been added. They will be deployed with the next release.
