### ISSUE TITLE
Roboland: Metal spiders

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#87]
same stats
Snook-8: they drop
Snook-8: 1 nugget
Snook-8: and chance for gold  35%
Snook-8: chance for gland 40%

**Comment by Snook-8** [comment]
Health 175
Damage 10
Attack Period 2
Attack Range 2.5
Walking Speed 2
Running Speed 4
Insanity Aura -35/min

**Comment by jchmb** [comment]
Done!
