### ISSUE TITLE
Roboland: Metal Spiders Den

### ISSUE THREAD

**Issue by Snook-8** [jchmb/dst-multiverse#88]
need hammer to be broken
Snook-8: and they drop their blueprint 50%

Snook-8: and 80% 2 more ore nugget

Snook-8: they dont caught fire

Snook-8:  100% 3 rocks

Snook-8: chance for 1 gold nugget 20%

Snook-8: the spider area no webs plz

Snook-8: also it doesnt produce spider warriors

**Comment by jchmb** [comment]
Done!
